name: Walmart Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5' # every Friday at 9:00 AM

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧱 Install required packages for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libdrm2 \
            libgbm1 \
            libasound2

      - name: 🚀 Run Puppeteer Script
        run: node WalmartTrigerData.js
